export const colleges = [
  { id: 101, name: "MIT Muzaffarpur", short: "MIT Muzaffarpur", tier: 1, location: "Muzaffarpur", estd: 1954, website: "https://www.mitmuzaffarpur.org" },
  { id: 102, name: "BCE Bhagalpur", short: "BCE Bhagalpur", tier: 1, location: "Bhagalpur", estd: 1960, website: "https://bcebhagalpur.ac.in" },
  { id: 103, name: "GCE Gaya", short: "GCE Gaya", tier: 2, location: "Gaya", estd: 2008, website: "https://gcegaya.ac.in" },
  { id: 106, name: "MCE Motihari", short: "MCE Motihari", tier: 2, location: "Motihari", estd: 1980, website: "https://mcemotihari.ac.in" },
  { id: 104, name: "DCE Darbhanga", short: "DCE Darbhanga", tier: 2, location: "Darbhanga", estd: 2008, website: "https://dcedarbhanga.ac.in" },
  { id: 105, name: "Nalanda College of Engineering, Chandi", short: "NCE Chandi", tier: 2, location: "Nalanda", estd: 2008, website: "https://ncechandi.ac.in" },
  { id: 107, name: "LNJPIT Chapra", short: "LNJPIT Chapra", tier: 3, location: "Chapra", estd: 2012, website: "https://lnjpit.ac.in" },
  { id: 108, name: "BCE Bakhtiyarpur", short: "BCE Bakhtiyarpur", tier: 3, location: "Patna", estd: 2016, website: "https://bcepatna.ac.in" },
  { id: 109, name: "SIT Sitamarhi", short: "SIT Sitamarhi", tier: 3, location: "Sitamarhi", estd: 2016, website: "https://sitsitamarhi.ac.in" },
  { id: 110, name: "RRSDCE Begusarai", short: "RRSDCE Begusarai", tier: 3, location: "Begusarai", estd: 2016, website: "https://rrsdce.ac.in" },
  { id: 111, name: "SCE Sasaram", short: "SCE Sasaram", tier: 3, location: "Rohtas", estd: 2016, website: "https://scesasaram.ac.in" },
  { id: 112, name: "B.P.M.C.E. Madhepura", short: "BPMCE Madhepura", tier: 4, location: "Madhepura", estd: 2016, website: "https://bpmcemadhepura.ac.in" },
  { id: 113, name: "K.C.E. Katihar", short: "KCE Katihar", tier: 4, location: "Katihar", estd: 2016, website: "https://kcekatihar.ac.in" },
  { id: 114, name: "Purnea College of Engineering", short: "PCE Purnea", tier: 2, location: "Purnea", estd: 2017, website: "https://pcepurnea.ac.in" },
  { id: 115, name: "Saharsa College of Engineering", short: "SCE Saharsa", tier: 4, location: "Saharsa", estd: 2017, website: "https://scesaharsa.ac.in" },
  { id: 116, name: "Supaul College of Engineering", short: "SCE Supaul", tier: 4, location: "Supaul", estd: 2017, website: "https://scesupaul.ac.in" },
  { id: 117, name: "Government Engineering College, Banka", short: "GEC Banka", tier: 5, location: "Banka", estd: 2018 },
  { id: 118, name: "Government Engineering College, Vaishali", short: "GEC Vaishali", tier: 5, location: "Vaishali", estd: 2018 },
  { id: 119, name: "Government Engineering College, Jamui", short: "GEC Jamui", tier: 5, location: "Jamui", estd: 2018 },
  { id: 120, name: "Government Engineering College, Nawada", short: "GEC Nawada", tier: 5, location: "Nawada", estd: 2018 },
  { id: 121, name: "Government Engineering College, Kishanganj", short: "GEC Kishanganj", tier: 5, location: "Kishanganj", estd: 2018 },
  { id: 128, name: "Shri Phanishwar Nath Renu Engineering College, Araria", short: "GEC Araria", tier: 6, location: "Araria", estd: 2019 },
  { id: 122, name: "Government Engineering College, Munger", short: "GEC Munger", tier: 5, location: "Munger", estd: 2018 },
  { id: 123, name: "Government Engineering College, Sheohar", short: "GEC Sheohar", tier: 5, location: "Sheohar", estd: 2018 },
  { id: 124, name: "Government Engineering College, West Champaran", short: "GEC Bettiah", tier: 6, location: "Bettiah", estd: 2018 },
  { id: 125, name: "Government Engineering College, Aurangabad", short: "GEC Aurangabad", tier: 6, location: "Aurangabad", estd: 2019 },
  { id: 126, name: "Government Engineering College, Kaimur", short: "GEC Kaimur", tier: 6, location: "Kaimur", estd: 2019 },
  { id: 132, name: "Government Engineering College, Gopalganj", short: "GEC Gopalganj", tier: 6, location: "Gopalganj", estd: 2019 },
  { id: 134, name: "Government Engineering College, Madhubani", short: "GEC Madhubani", tier: 6, location: "Madhubani", estd: 2019 },
  { id: 137, name: "Government Engineering College, Siwan", short: "GEC Siwan", tier: 6, location: "Siwan", estd: 2019 },
  { id: 133, name: "Government Engineering College, Jehanabad", short: "GEC Jehanabad", tier: 6, location: "Jehanabad", estd: 2019 },
  { id: 129, name: "Government Engineering College, Arwal", short: "GEC Arwal", tier: 6, location: "Arwal", estd: 2019 },
  { id: 127, name: "Government Engineering College, Khagaria", short: "GEC Khagaria", tier: 6, location: "Khagaria", estd: 2019 },
  { id: 131, name: "Government Engineering College, Buxar", short: "GEC Buxar", tier: 6, location: "Buxar", estd: 2019 },
  { id: 130, name: "Government Engineering College, Bhojpur", short: "GEC Bhojpur", tier: 6, location: "Ara", estd: 2019 },
  { id: 136, name: "Government Engineering College, Sheikhpura", short: "GEC Sheikhpura", tier: 6, location: "Sheikhpura", estd: 2019 },
  { id: 138, name: "Government Engineering College, Lakhisarai", short: "GEC Lakhisarai", tier: 6, location: "Lakhisarai", estd: 2019 },
  { id: 135, name: "Government Engineering College, Samastipur", short: "GEC Samastipur", tier: 6, location: "Samastipur", estd: 2019 },
  { id: 139, name: "DR. C.P. Thakur Institute", short: "CP Thakur Inst.", tier: 6, location: "Patna", estd: 2021 },
  { id: 140, name: "CIPET:IPT, Bihta, Patna", short: "CIPET Bihta", tier: 3, location: "Bihta", estd: 2020 },
  { id: 141, name: "S.G.I.D.T. Patna", short: "SGIDT Patna", tier: 4, location: "Patna", estd: 2020 },
  { id: 142, name: "Women's Institute of Tech, Darbhanga", short: "WIT Darbhanga", tier: 4, location: "Darbhanga", estd: null }
];
// Cutoff data is now served via /public/data/cutoffs.json for max performance and low memory.
